---
- name:           Installing packages
  yum:            name={{ item }} state=present
  with_items:
    - lsof
    - unzip
    - tar
    - wget
    - glibc.x86_64
    - libgcc.x86_64
    - libstdc++.x86_64
#    - glibc.i686
#    - libgcc.i686
#    - libstdc++.i686
  when:           (ansible_distribution == "RedHat") or (ansible_distribution == "CentOS")

- name:           Create domino group
  group:
    name:         "{{ __dom_group }}"
    state:        present

- name:           Create domino user
  user:
    name:         "{{ __dom_user }}"
    group:        "{{ __dom_group }}"
    state:        present

- name:           Is limits.conf already changed?
  command:        "egrep {{ __dom_user }} /etc/security/limits.conf"
  register:      limits_ok
  ignore_errors: true

- name:           Define limits.conf
  lineinfile:
    dest:         /etc/security/limits.conf
    insertbefore: "# End of file"
    line:         "{{ __dom_user }}           {{ item.type }}    nofile          {{ item.value }}"
  with_items:
      - { type: "soft", value: "60000"}
      - { type: "hard", value: "80000"}
  when:          limits_ok.rc != 0

- name:           Create notesdata directory
  file:
    path:         "{{ __dom_notesdata }}"
    state:        directory
    owner:        "{{ __dom_user }}"
    group:        "{{ __dom_group }}"
