---
- name:          Cleanup Binaries directory
  file:          path={{ __tmp_dir }} state=absent
  ignore_errors: true

- name:          Create Binaries directory
  file:          path={{ __tmp_dir }} state=directory mode=0755

- name:          Create Logs directory
  file:          path={{ __logs_dir }} state=directory mode=0755

- name:          Download IBM Domino
  get_url:
    url:         "{{ __repository_url }}/{{ __bin_file }}"
    dest:        "{{ __tmp_dir }}/{{ __bin_file }}"
    mode:        0755
    checksum:    sha256:{{ __bin_file_sha256 }}

- name:          Extract IBM Domino
  unarchive:
    src:         "{{ __tmp_dir }}/{{ __bin_file }}"
    dest:        "{{ __tmp_dir }}/"
    copy:        no
    creates:     "{{ __tmp_dir }}/{{ __os }}/domino/install"

- name:          Generate Domino Install Response file
  template:
    src:         "{{ __tpl_file }}"
    dest:        "{{ __rsp_file }}"

- name:          Install IBM Domino Software
  shell:
    "{{ __tmp_dir }}/{{ __os }}/domino/install -silent -options {{ __rsp_file }}"
  args:
    chdir:       "{{ __tmp_dir }}/{{ __os }}/domino"
    creates:     "{{ __dom_install_location }}/bin/server"

- name:          Cleanup Binaries directory
  file:          path={{ __tmp_dir }} state=absent
