---
- include:            check-version.yml

#TODO: Change this for Domino v10
- include:            config-os.yml
  when:               __release < __this_version[0:3]

#- include:            domino-server-stop
#  when:               __release < __this_version[0:3]

- include:            inst-domino.yml
  when:               __release < __this_version[0:3]
