---
__repository_url:        "{{ domino_repository_url }}"
__tmp_dir:               "{{ tmp_dir | default('/opt/Binaries') }}/domino"
__logs_dir:              "{{ tmp_dir | default('/opt/Binaries') }}/logs"

__dom_install_location:  "{{ domino_install_location | default('/opt/ibm/domino') }}"
__dom_notesdata:         "{{ domino_notesdata | default('/domino/notesdata') }}"
__dom_user:              "{{ domino_user      | default('notes') }}"
__dom_group:             "{{ domino_group     | default('notes') }}"

__bin_file:              "{{ domino_bin_file | default('DOMINO_9.0.1_64_BIT_LIN_XS_EN.tar') }}"
__bin_file_sha256:       "{{ domino_bin_file_sha256 | default('9f5f941ec43ca268197cb1250a2677630789a4efeca73d38d69ebecd7d32870a') }}"
__this_version:          "{{ domino_version | default('90010') }}"

__now:                   "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:              "{{ __logs_dir }}/domino_install.rsp"
__log_file:              "{{ __logs_dir }}/domino_install.{{ __now }}.log"
__tpl_file:              "domino_install.rsp.j2"
__os:                    "{{ ansible_system | lower }}64"

__release_str:               "000"
__fp_str:                    "0"
__hf_str:                    "0"

__release:               0
__fp:                    0
__hf:                    0
